### ISSUE TITLE
[Suggestion] Allow for deeper customization outside of block generation

### ISSUE THREAD

**Issue by Uziskull** [rutgerkok/WorldGeneratorApi#3]
Right now, if I want to edit the part of the generation that has to do with underground lakes (those belong to the `ChunkStatus.LIQUID_CARVED` status of chunk creation), I have to use reflection to access those classes. Or, even if I want to edit something a bit less tricky, like lower bedrock generation (which belongs to `ChunkStatus.BASE`, like block generation does), I have to edit your `InjectedChunkGenerator` class (specifically, the `createChunk` method).

Ideally, it would be great if these were able to be customized by simply using your API. Some of these might be tricky to provide customization for, but at least an option to be able to generate flat bedrock would be easily doable and would provide a higher level of customization.

**Comment by rutgerkok** [comment]
Yeah, this is definitely something that is needed in the API. Right now, I'm working on making it compatible with Paper's async chunk generation feature, but after that I'll implement this.

**Comment by rutgerkok** [comment]
Ok, both issues have now been addressed. The WorldDecorator interface now contains methods to control both. I introduced "base decorations", which operate on a single chunk, instead of a 2x2 chunk area like most other decorations do.

* To disable underwater caves and ravines, use `worldDecorator.setDefaultDecoratorsEnabled(DecorationType.CARVING_LIQUID, false)`.
* To disable the small underwater lakes, use `worldDecorator.setDefaultDecoratorsEnabled(DecorationType.LOCAL_MODIFICATIONS, false)`. (This was already possible before).
* To disable bedrock generation, use `worldDecorator.setDefaultBaseDecoratorsEnabled(BaseDecorationType.BEDROCK, false)`.
* To add custom generation of any of the above, use `worldDecorator.withCustomDecoration(..)` or `worldDecorator.withCustomBaseDecorator(..)`.
