### ISSUE TITLE
Nether, or End?

### ISSUE THREAD

**Issue by tastybento** [rutgerkok/WorldGeneratorApi#33]
Is there a way to generate the Nether or End? I tried to work out, but I'm stumped.

**Comment by rutgerkok** [comment]
WorldGeneratorApi doesn't do anything special here, so I've just listed how you would normally create a Nether or End world on Spigot/Paper:

* If you aren't using a multiworld plugin, just modify world_nether instead of world
* If you are using a multiworld plugin (like Multiverse), just create a world with the correct environment.
* If you are creating a world through the Bukkit API, use [WorldCreator.environment(World.Environment.NETHER)](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/WorldCreator.html#environment(org.bukkit.World.Environment)) (or THE_END)

**Comment by tastybento** [comment]
Just to clarify, when you say "WorldGeneratorApi doesn't do anything special here", do you mean that WorldGeneratorApi doesn't support Nether generation?

I made a nether world and used the `generator.setBaseNoiseGenerator` and gave it some noise, but ended up with essentially an overworld in the nether:
<img width="824" alt="Screen Shot 2021-03-21 at 10 45 59 PM" src="https://user-images.githubusercontent.com/4407265/111945900-c2edef00-8a97-11eb-9c69-0125a71e3efc.png">

I'm was trying to make a nether world with my own generation functions and biome definitions like I did in the overworld.

**Comment by rutgerkok** [comment]
Looks like it's already working. Now you need to make two changes to make your noise generator create more Nether-like terrain:

* Override the `getTerrainSettings()` method in your noise generator, and make it return an object with the correct stoneBlock (netherrack) and the correct waterBlock (lava).
* Change you noise function to also return positive values at higher altitude, so that landmass is generated there.
