### ISSUE TITLE
Structure generation

### ISSUE THREAD

**Issue by tastybento** [rutgerkok/WorldGeneratorApi#35]
Is there anyway to "force" structures to generate, like villages, etc., rather than rely on random generation?

**Comment by rutgerkok** [comment]
This would be nice, but creating such an API would involve editing the code of each and every structure, so that's too much to handle for this API. Your best bet is to use the vanilla Custom world settings ( https://minecraft.fandom.com/wiki/Custom ) to modify the spawning settings. (Or if you want a village at a very specific place, just build it yourself with WorldEdit.)
