### ISSUE TITLE
Error: WorldGenSettings: Unknown registry element Field[[WorldGeneratorApi]

### ISSUE THREAD

**Issue by hawkfalcon** [rutgerkok/WorldGeneratorApi#36]
**Describe the bug**
An error shows up occasionally in console

**To Reproduce**
I've implemented a super simple biome replacement. Occasionally in console this occurs:
[04:56:18 ERROR]: WorldGenSettings: Unknown registry element Field[[WorldGeneratorApi] Custom biome generators cannot be stored in the level.dat, please ignore this error: Registry[ResourceKey[minecraft:root / minecraft:worldgen/biome] (Stable)]][xmapped]

I'm running a current version of paper, and the latest worldgeneratorapi

**Comment by rutgerkok** [comment]
This is because custom biome generators cannot be stored in the level.dat file. Normally, the level.dat file will save something like "biome_source": "minecraft:vanilla_layered". To fix this, the API will need to be changed so that biome generators are first registered.

I don't know if you saw it, but the error message itself says that it can be ignored.
