### ISSUE TITLE
World Generation reverts back to its own populator after a plugin or server reload initiates 

### ISSUE THREAD

**Issue by apollyon600** [rutgerkok/WorldGeneratorApi#38]
**Describe the bug**
WorldGeneratorAPI isn't generating the rest of the world after a server restart (or plugin reload).

**To Reproduce**
1. Create a BiomeGenerator, or something that alters the current vanilla world
2. Handle the `WorldGeneratorInitEvent` Event and implement the BiomeGenerator
3. Load up a world, generate a few chunks, restart the server or reload the plugin
4. The BiomeGenerator no longer stays with the world generation, thus reverting back to its original block populator

**Screenshots**
![image](https://user-images.githubusercontent.com/41652412/118200571-45e15500-b40a-11eb-9928-4ef2e7e30f35.png)

**Comment by rutgerkok** [comment]
Just a quick check: are you setting the biome generator again after a server restart? (Setting a biome generator doesn't persist through restarts or reloads.)

**Comment by apollyon600** [comment]
> Just a quick check: are you setting the biome generator again after a server restart? (Setting a biome generator doesn't persist through restarts or reloads.)

Nope, I thought it was stored into the world folder but it doesn't seem like it.

**Comment by rutgerkok** [comment]
Ah ok!

Nowadays Minecraft stores the names of the various parts of the world generator in the level.dat for customized worlds. However, currently WorldGeneratorApi doesn't use names anywhere. For 1.17, it would be interesting to rework WorldGeneratorApi so that it asks the plugin developer to provide a name everywhere, and then stores that in the customized world settings.
